### ISSUE TITLE
Handling push/popViewController

### ISSUE THREAD

**Issue by benbonnet** [IconoclastLabs/RubyMotion-Custom-Transitions#1]
What would be a proper way to use pushViewController with a custom animations ?

There are loads of examples in iOS; but I might miss a dot somewhere to port it to ruby motion; and can't find an entry point

thx if you have more infos about it
btw you're the only google-findable source about custom transition in ruby motion

**Comment by GantMan** [comment]
YAY for being found :)

I should push this repo a bit harder sometime.   Did you see the blog post here?   http://www.iconoclastlabs.com/blog/custom-controller-transitions-in-rubymotion

As you can see in the code, I do used pushViewController, because the NavigationController has been set with the correct animation delegate.

https://github.com/IconoclastLabs/RubyMotion-Custom-Transitions/blob/master/app/controllers/step1_controller.rb#L21

Does that help?

**Comment by benbonnet** [comment]
hey thanks for your reply ! your post put me on the way for sure
but I have a bit more to experiment; so I don't want to bother. but if you have a piece of time…

Correct me if I'm wrong, you two uinavigtioncontroller :
- one in app_delegate (ruby motion's default, from what I understand so far has no 'real' use in your example)
- another one in main controller (the interesting ones, on which you apply the custom transitions)

as I'm learning, having two is a bit confusing

Thing is that I really don"t understand why you can't use pushviewcontroller here (https://github.com/IconoclastLabs/RubyMotion-Custom-Transitions/blob/master/app/controllers/main_controller.rb#L23)

I have this so far : https://github.com/bbnnt/rubymotion.pushViewController.customTransition, trying to stick with a dingle uinavigationcontroller
But could not put all the concerned elements in a custom class as you did (setting the delegate in every controllers, having also `def navigationController...` for each)

**Comment by GantMan** [comment]
My example has 2 buttons.  One that will do custom animations between two controllers, and one that doesn't.   That's not a common thing to do, so you'll want to have custom animations right away.

In your code, just set your navigation controller delegate to a custom transition in the app delegate.

**Comment by benbonnet** [comment]
in any case that actually helped a lot, thx for you example. Always easier to read/understand ruby syntax !
I'll always wonder why `@step.delegate = CustomTransition.new` would not work tough (instead of splitting as you did `@transition = CustomTransition.new; @step.delegate = @transition`)

**Comment by GantMan** [comment]
good question.   Definitely link me to anything you find out.   I'm glad this helped!
